### ISSUE TITLE
Link from drake's documentation

### ISSUE THREAD

**Issue by wlandau** [pat-s/pathogen-modeling#1]
@pat-s, may I link to this repo from `drake`'s documentation? I think this is a great project to illustrate the problem `drake` is trying to solve. Ref: https://github.com/wlandau/drake-examples/issues/11.

- https://github.com/ropensci/drake#real-example-projects
- https://ropenscilabs.github.io/drake-manual/#real-example-projects

cc @karthik

**Comment by pat-s** [comment]
@wlandau This study is now finished. Feel free to link it :) Overall, this work has 308 targets.

It will hopefully soon be accepted by the Journal.

**Comment by wlandau** [comment]
Fantastic, congratulations @pat-s! I will link to it.
